#!/bin/python2
# -*- coding: utf-8 -*-

print('E' * 25)
print(" \nDeath \n\nYou died. \n\nTHE END \n")
print('-' * 25)
print(" \nLower Deck Cursive \n\nThe Gothon pirates have boarded your ship. You \nare the last standing crew member. No surprise! \nWhile your comrades were fighting, you were... \nsleeping! Anyhow, this vessel must not fall into \nenemy's hands. You are now running down the lower \ndeck cursive. A safe choice to avoid enemies. \nAhead: the armory. As you emerge from the last \nhatch, one insectoid pirate jumps out, guarding \nthe way to the armory. He's about to pull a \nweapon to blast you. What do you do? \n\n[a] shoot! [b] dodge! [c] tell a joke \n")
print('-' * 25)
print(" \nEpilogue \n\nQuick on the draw, you yank out your blaster and \nfire it at the Gothon pirate. He leaps high in \nthe air. Your laser misses him entirely. The \npirate flies into an insane rage and blast you \nrepeatedly in the face until you are dead. Then, \nthe insectoid dissolves you with his saliva, and \nsuck you up. \n\nTHE END \n")
print('-' * 25)
print(" \nEpilogue \n\nYou dodge, weave, and slide as the pirate's \nblaster cranks a laser past your head. In the \nmiddle of your artful dodge, your foot slips. You \nbang your head on the wall, and pass out. You \nwake up shortly after, only to die as the \ninsectoid dissolves you with his saliva, and suck \nyou up. \n\nTHE END \n")
print('-' * 25)
print(" \nThe Armory \n\nLucky for you they made you learn Gothon insults \nin the academy.  You tell the one Gothon joke you \nknow. The Gothon stops, waits, then busts out \nlaughing. While he's laughing, you shoot him \nsquare in the head, putting him down. You then \njump through the armory door. It's dead quiet... \nYou lock the door and run to the far side of the \nroom. All the laser weapons are gone. You find \nthe explosive container. There is a keypad lock \non the box. You need a 3-digit code to get the \nbomb out. You can guess. Howerver, after five \nattempts, you know the lock will fuse forever. \n\nEnter three digits. \n")
print('-' * 25)
print(" \nThe Armory \n\nNot working. Try again. \n\nEnter three digits. \n")
print('-' * 25)
print(" \nThe Armory \n\nNot working. Hurry up! You remember that all the \ndigit combinations aboard begin with \'1\', plus \ntwo digits. \n")
print('-' * 25)
print(" \nThe Armory \n\nNot working. Come on! Try again. The code begins \nwith \'1\', plus two digits. \n")
print('-' * 25)
print(" \nThe Armory \n\nNot working. Mmmmh... OK! OK! OK! You remember. \nThese combinations are always made with digits \n\'1, 2, and 3\'! Hence, \'1\', plus two digits. \n")
print('-' * 25)
print(" \nEpilogue \n\nThe lock buzzes once more. Only this time, you \nhear a sickening melting sound. The mechanism is \nfused together. Without weapon: no hope. You \ndecide to sit there. Time passes... and passes... \nSuddenly, you hear a muffled thud. Something hit \nthe ship? Then, another thud? And, more thuds. \nThis time, heavier and louder. The hull begins \nshaking and roaring. Soon, the temperature falls, \nair pressure drops, oxygen becomes scarcer… \nThey let the ship strand on the asteroid belt!! \nYou fall into a faint... to never wake up again. \n\nTHE END \n")
print('-' * 25)
print(" \nThe Bridge \n\nThe container clicks open, the seal breaks, \nletting gas out. You find a dozen of time-bombs. \nYou grab one. You run as quickly as you can to \nthe starboard engine. Over there, you know the \nblast will trigger a chain reaction and destroy \nthe ship. You burst onto the bridge with your \nbomb under your arm. You surprise three Gothon \npirates. The three lezardoids haven't pulled \ntheir weapons out yet, as they see the active \nbomb under your arm. What do you do? \n\n[a] throw the bomb [b] slowly place the bomb \n")
print('-' * 25)
print(" \nEpilogue \n\nIn a panic, you trigger off the timer, throw the \nbomb and make a leap for the door. Right as you \ndrop it, a pirate shoots you in the back, killing \nyou. As you die you see another pirate \nfrantically trying to disarm the bomb. They got \nyou, but they won't make it alive either. \n\nTHE END \n")
print('-' * 25)
print(" \nEscape Pod \n\nYou point your blaster at the bomb under your \narm. The pirates put their hands up. You inch \nbackward to the door and then carefully place the \nbomb on the floor, pointing your blaster at it. \nThen you set off the timer, jump back through the \ndoor, punch the close button and blast the lock. \nNow, you must reach the escape pods to get off \nthis tin can. You get to the boarding bay. \nSuddenly, the ship rattles! The bomb just \nexploded. The reactor will melt down and the ship \nwill soon be disintegrated! There are five pods, \nwhich one do you take? \n\nEnter a digit, from 1 to 5. \n")
print('-' * 25)
print(" \nEscape Pod \n\nAs you are about to punch the keypad, a voice \nfrom within you murmurs: \’Be careful... the \npods are trapped. Don't take odd numbers.\’ \n")
print('-' * 25)
print(" \nEscape Pod \n\nThe voice goes again: \’Be careful...\’ \n")
print('-' * 25)
print(" \nEpilogue \n\nYou punch the keypad, the airlock opens, you jump \ninto the pod. From the dark, you catch sight of a \ntiny red light floating towards you. This hiss? \nYou are face to face with a combat drone. The \nlast thing you notice is being disintegrated by a \nlaser blast. \n\nTHE END \n")
print('-' * 25)
print(" \nEpilogue \n\nYou punch the keypad, the airlock opens, you jump \ninto the pod, and trigger the evasion procedure. \nThe pod easily slides out into space, heading to \nthe planet below. VICTORY! You look in the \nporthole and see your ship explode like a bright \nstar, taking out the Gothon ship at the same \ntime… \n\nTHE END \n")
print('-' * 25)
print('F' * 25)
print('-' * 25)
print(" \nMort \n\nTu meurs. \n\nFIN \n")
print('-' * 25)
print(" \nCoursive du pont inférieur \n\nLes pirates gothons ont abordé ton vaisseau. Tu \nes le seul survivant de l’équipage. \nÉvidemment, alors que tes camarades \ncombattaient, tu... dormais! Peu importe, ce \nvaisseau ne doit pas tomber aux mains de \nl’ennemi. Te voilà donc à la course dans la \ncoursive du pont inférieur. Judicieux pour \néviter les ennuis. Droit devant: l'arsenal. \nAlors que tu t’extrais de la dernière \nécoutille, un pirate insectoïde fait irruption. \nIl bloque l’entrée de l'arsenal. Il \ns’apprête à dégainer pour te griller. Que \nfais-tu? \n\n[a] tire! [b] esquive! [c] raconte une blague \n")
print('-' * 25)
print(" \nÉpilogue \n\nRapide sur la gâchette, tu fais cracher ton \nlaser en direction du pirate gothon. Ce dernier \nbondit dans les airs. Tu le rates. Fou de rage, \nle pirate bondit vers toi et te balance quelques \ndécharges à la tête. Tu t’effondres. Puis, \nl’insectoïde te liquéfie avec sa salive, \navant de t’aspirer. \n\nFIN \n")
print('-' * 25)
print(" \nÉpilogue \n\nLe pirate te balance des jets de laser; tu les \nesquives. Dans ce ballet improvisé, tu finis par \nglisser. Ta tête donne contre le mur. Tu \nt’assommes et t’écroules. Tu ne reprends \nconnaissance que pour te rendre compte que \nl’insectoïde te liquéfie avec sa salive, \navant de t’aspirer. \n\nFIN \n")
print('-' * 25)
print(" \nL'Arsenal \n\nTu trouves bien utile d’avoir mémorisé un peu \nde gothon à l’académie.  Tu racontes donc la \nseule blague dont tu te souviens. Le Gothon fige, \nréfléchit, puis éclate de rire. Alors qu’il \ns’esclaffe, tu lui balances un jet laser à la \ntête. Il s’écroule. Tu enjambes le corps et \npénètres dans l'arsenal. Il règne un silence \nmortuaire... Tu verrouilles la porte et \nt’élances vers le fond de la pièce. Les armes \nlaser ont été emportées. Tu retrouves le \nconteneur à explosifs. Pour l’ouvrir, tu dois \nentrer un code à trois chiffres sur le clavier. \nTente de deviner. Par contre, après cinq \ntentatives, le verrou se soude à jamais. \n\nEntre trois chiffres. \n")
print('-' * 25)
print(" \nL'Arsenal \n\nNon. Essaie encore. \n\nEntre trois chiffres. \n")
print('-' * 25)
print(" \nL'Arsenal \n\nRaté. Dépêche-toi! Tu te rappelles que les \ncombinaisons à bord débutent par \'1\', plus \ndeux chiffres. \n")
print('-' * 25)
print(" \nL'Arsenal \n\nRaté. Aller! Essaie encore. Le code débute par \n\'1\', plus deux chiffres. \n")
print('-' * 25)
print(" \nL'Arsenal \n\nRaté. Mmmmh… OK! OK! OK! Ça revient. Les \ncombinaisons ne comportent que les chiffres \'1, \n2 et 3\'! Donc, \'1\' plus deux chiffres. \n")
print('-' * 25)
print(" \nÉpilogue \n\nLe verrou bourdonne une dernière fois et tu \nl’entends se souder. Le mécanisme a sauté. \nSans arme, c’est l’impasse. Tu décides de \nt’assoir. Le temps passe… et passe... \nSoudain, tu entends un bruit sourd. Quelque chose \na percuté le vaisseau? Puis, un autre bruit? Et \nencore. De plus en plus lourd et fréquent. La \ncoque vrombit et grince. L’air se refroidit, la \npression chute, l’oxygène se raréfie… Ils \nont laissé le vaisseau s’échouer dans la \nceinture d’astéroïdes!! Tu t’évanouis… \npour ne jamais te réveiller. \n\nFIN \n")
print('-' * 25)
print(" \nLe pont \n\nLe verrou se déclenche, le scellant se fend, le \ncontenant se dépressurise. Tu prends une des \ndouzaines de bombes à retardement. Tu te diriges \nà la hâte vers le réacteur du tribord. Une \nexplosion y déclenchera une réaction en chaine \net détruira le vaisseau. Tu émerges sur le pont \ndu réacteur et tu surprends trois pirates \ngothons. Les trois lézaroïdes n’ont pas \nencore dégainé, mais ils fixent la bombe que tu \nportes. Que fais-tu? \n\n[a] lance la bombe [b] dépose la bombe \n")
print('-' * 25)
print(" \nÉpilogue \n\nEn panique, tu déclenches la minuterie et tu \nbalances la bombe. Alors que tu t’élances vers \nla porte, un pirate te tire mortellement dans le \ndos. Tu perds connaissance en voyant les pirates \ndésespérément essayer de désarmer l’engin \nexplosif. Ils t’ont eu, mais ils y passeront \neux aussi. \n\nFIN \n")
print('-' * 25)
print(" \nNavette de secours \n\nTu pointes ton laser vers la bombe que tu tiens. \nLes pirates lèvent les bras. Tu recules vers la \nporte et tu poses délicatement la bombe au sol \ntout en la maintenant en joue. Puis, tu \ndéclenches la minuterie, passes la porte, \nfrappes le bouton de fermeture et fais sauter la \nconsole. Maintenant, tu dois gagner les navettes \nde secours pour t’éjecter du vaisseau. Tu \natteins la zone d’embarquement. Soudain, le \nvaisseau tremble! La bombe vient d’exploser. Le \nréacteur va se fissurer et le vaisseau va \nbientôt se disloquer! Il y a cinq navettes, \nlaquelle choisis-tu? \n\nEntre un chiffre, de 1 à 5. \n")
print('-' * 25)
print(" \nNavette de secours \n\nComme tu t’apprêtes à ouvrir le sas, une voix \nen toi te murmure: \’Attention… elles sont \npiégées. Ne prends pas les numéros impairs.\’ \n")
print('-' * 25)
print(" \nNavette de secours \n\nLa voix te murmure encore: \’Attention…\’ \n")
print('-' * 25)
print(" \nÉpilogue \n\nTu frappes le bouton d’ouverture, le sas \ns’ouvre, tu bondis à l’intérieur. Dans \nl’obscurité, tu aperçois un voyant rouge \nflotter vers toi. Ce crépitement? Tu fais face \nà un drone de combat. En moins de deux, tu es \ndésintégré alors que le drone décharge son \nlaser. \n\nFIN \n")
print('-' * 25)
print(" \nÉpilogue \n\nTu frappes le bouton d’ouverture, le sas \ns’ouvre, tu bondis à l’intérieur, puis tu \nenclenches la procédure d’évacuation. La \nnavette s’éjecte dans l’espace, puis ajuste \nsa trajectoire sur la planète. VICTOIRE! Tu \nregardes dans le hublot et tu assistes à \nl’explosion de ton vaisseau. L’onde de choc \nemporte le vaisseau gothon… \n\nFIN \n")
print('-' * 25)
